### ISSUE TITLE
Can not do JQL queries (unclear) 

### ISSUE THREAD

**Issue by rondlite** [StudioWhyNot/AgileBot#5]
> Custom JQL and other advanced Queries are also available. For now, you can see them in Commands.cs.

I tried many combos and managed to get errors about the jql but did not manage any of the order,orderby, jql queries.
Can you give a small example of those?

**Comment by ScionOfDesign** [comment]
The syntax is as follows:
!tasks jql: "status = Done AND assignee = scion AND createdDate <=  '2021/06/30' AND createdDate >=  '2021/06/29' ORDER BY priority DESC"

Any of the fields in TaskParams can be assigned with `fieldName`:`"fieldValue"` as documented [here ](https://discordnet.dev/guides/text_commands/namedarguments.html) by Discord.NET.

Passing in the Jql field will ignore any other passed-in fields.

I will update the documentation to be more clear on how to pass in fields.

**Comment by ScionOfDesign** [comment]
Resolved with: 1c6fe54bb4d573f3612455fef3eee42f69d045da

**Comment by rondlite** [comment]
It was the `:` that I was missing, is clear now
